version: '2'

services:
  postgres:
    image: postgres:9.6-alpine
    # environment:
      # POSTGRES_USER: 'postgres_user'
      # POSTGRES_PASSWORD: 'postgres_password'
    volumes:
      - postgres:/var/lib/postgresql/data

  website:
    build: .
    volumes:
      - .:/app_name
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    # env_file: .env

volumes:
  postgres:
